export type MemeTypes =
    | 'random'
    | 'dank'
    | 'danker'
    | 'prequel'
    | 'facebook'
    | 'wholesome'
    | 'deepfried'
    | 'surreal'
    | 'funny'
    | 'last'
    | 'economy'
    | 'cats'
    | 'dogs'
